### ISSUE TITLE
correct_time() not working as expected

### ISSUE THREAD

**Issue by bramdhondt** [MarcusRowcliffe/camtrapDensity#2]
I greatly welcome the function `correct_time()`, as this helps avoid cumbersome scripting in the not-so-rare case of wrong time settings of cameras.

When applying the logic of [the example](https://github.com/MarcusRowcliffe/camtrapDensity/blob/master/README.md) to my dataset, the function doesn't fully correspond to my expectations, however. To illustrate, I start with the following list of deployments (trimmed list).

![afbeelding](https://user-images.githubusercontent.com/78358923/224292763-56757a90-e3e7-407e-93fe-0af0355dbfcc.png)

As you can see, the last deployment is an oddball: it was not installed, nor read out, that late in the evening. The time settings of the camera are simply wrong.

Applying the following code...

```
sub <- correct_time(sub,
                   deploymentID = "c8008e80-3684-4ee0-a491-0e11a7d55918",
                   wrongTime = "2023-01-12 23:07:50",
                   rightTime = "2023-01-13 12:00:00")
```

... leads to the following result.

![afbeelding](https://user-images.githubusercontent.com/78358923/224293897-ded4b218-9fe8-4c4e-bffe-8bc25cc62f7f.png)

The requested time span was successfully added to both the end and start time of the respective deployment. But contrary to expectations, the same time span was added to all deployments.  I assume this was not intended. I also don't find a solution in the function's documentation.

Apart from this, I congratulate you with this great package. At INBO, the REM functions of the package are now in use for estimating the abundance of a local muntjac population - a species of great policy concern to us.

**Comment by MarcusRowcliffe** [comment]
@bramdhondt many thanks for raising this and your clear explanation. There was indeed a foolish mistake, now fixed I believe. Let me know if not.
